### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by starlightknown** [Creatoon/Jar-web-app#25] opened 2021-05-21 16:42 UTC
add code of conduct to the project

**Comment by nisha331** [comment] 2021-06-12 20:37
As the project does not contain code of conduct file I would like to add it.
I am a LGMSOC'21 participant kindly assign it to me.

**Comment by Creatoon** [comment] 2021-06-12 21:45
@nisha331 ok go ahead.

**Comment by nisha331** [comment] 2021-06-13 15:00
Sent a PR kindly check it, and the issue is not assigned so assign it if neccesary.  
Thank you

**Comment by Creatoon** [comment] 2021-06-13 15:44
@nisha331 Really appreciate you for this work, actually we don't assign issue to anyone, we simply follow first come and take policy.

**Closed as completed** 2021-06-13 15:44 UTC
Labels: documentation, 🤩 Up for Grab, 🟨 Level2, LGMSOC21
